apiVersion: apps/v1
kind: Deployment
metadata:
  name: asma-28086-redis-deployment
  labels:
    app: redis
    env: production
spec:
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 28086
