apiVersion: v1
kind: Pod
metadata:
  name: asma-28086-redis-pod
  labels:
    app: redis
    env: production
spec:
  containers:
    - name: redis-container
      image: redis:latest
      ports:
        - containerPort: 28086
